spring:
  application:
    name: eureka03     #应用名称，也是服务注册的名称

server:
  port: 8089         #开启端口

eureka:
  instance:
    hostname: peer3     #主机名
  client:
    serviceUrl:
      defaultZone: http://peer1:8081/eureka/,http://peer2:8088/eureka/ #与Eureka Server交互的地址，查询服务和服务注册都需要依赖这个地址
      #默认为http://localhost:8761/eureka,  多个地址用","分割
    fetch-registry: false                           #是否将自己注册到Eureka Server 默认为true
    register-with-eureka: true                     #是否从Eureka Server查询注册信息
  server:
    enable-self-preservation: false             #关闭自我保护模式
    eviction-interval-timer-in-ms: 4000         #清理服务间隔4s，默认60*10000